mia-platform/crud-service

docs/10_Overview_and_Usage.md
Update the documentation to highlight security suggestion for crud oss.
=> docs: crud oss security

.github/workflows/nodejs.yml, README.md
- Updated the `nodejs.yml` to build the docker image (and publishing to DockerHub and Github Registry) after tests when merging Pull Requests to `main` branch;
- Updated the `README.md` file:
- adding links to the published images;
- updated description on how to create docker images;
- included disclaimer on the usage of MongoDB Data Encryption
=> feat: updated pipeline to publish image to docker container

.gitignore, README.md, package.json
The intended way to work with the CRUD Service in local environment is to:
- clone the `default.env` file;
- use the cloned file when running the application;
Because we want to avoid that users updates the `default.env` for their need (and accidentally try to push updates to this file).
So, we use the `local.env` file from now on.
README.md file is updated to reflect this change.
=> fix(build): npm run start:local to use local.env file

README.md
=> fix(docs): Fixed typo on README.md

docs/10_Overview_and_Usage.md, docs/30_Encryption_configuration.md, docs/40_Performance_Overview.md
Small typos on the documentation and wrong information, fixed examples code formatting. Removed also a useless `.gitkeep`.
=> fix: typos on docs and in some code blocks

.github/workflows/nodejs.yml
Change the NodeJS Github workflow, so that it does not fail anymore in case the coverage decreases.
Obviously, this means that when merging PR the reviewer/assignee should have a look at the coverage result before introducing the changes in the main branch.
=> CI: review handling coverage Github action result

Dockerfile, README.md, docs/20_Configuration.md, lib/model.jsonschema.js, tests/viewsDefinitions/felines.js, tests/viewsDefinitions/store-open.js
This MR aims at improving repository description, especially clarifying the details regarding collection and view model definition. In addition, it is added a note regarding `__STATE__` field, highlighting the fact that such property must exists in records produced by view aggregation pipelines.
It also upgrades NodeJS version of the CRUD Service image to `v18.15.0`.
- [] Tests for the changes have been added (for bug fixes / features)
=> docs: review README and improved data model definition description

README.md
fix link from localhost to internal documentation
=> Update Readme.md - Fix link

CHANGELOG.md, lib/JSONSchemaGenerator.js, tests/expectedSchemas/booksPatchBulkSchema.js, tests/expectedSchemas/booksPatchManySchema.js, tests/expectedSchemas/booksPatchSchema.js, tests/expectedSchemas/booksUpsertOneSchema.js, tests/expectedSchemas/stationsPatchBulkSchema.js, tests/expectedSchemas/stationsPatchManySchema.js, tests/expectedSchemas/stationsPatchSchema.js, tests/expectedSchemas/stationsUpsertOneSchema.js, tests/httpInterface.patchById.test.js
Support for mongo operators to $addToSet
- [] Docs have been added / updated (for bug fixes / features)
=> feat: support mongo operators in $addToSet

CHANGELOG.md, lib/httpInterface.js, tests/httpInterface.changeStateBulk.test.js, tests/httpInterface.patchById.special.test.js, tests/httpInterface.postList.test.js
Additional properties error message now tells to the user the additional property that caused the error.
This PR closes #5
=> feat(Validation message): Improve validation error additional properties

CHANGELOG.md, Dockerfile, docs/20_Configuration.md, index.js, lib/httpInterface.js, lib/joinPlugin.js, package-lock.json, package.json, tests/httpInterface.changeStateBulk.test.js, tests/httpInterface.countList.test.js, tests/httpInterface.getList.test.js, tests/httpInterface.patchById.special.test.js, tests/httpInterface.postBulk.test.js, tests/httpInterface.postList.test.js, tests/integration.test.js, tests/utils.js
Upgrade lc39 to use v7, which uses fastify to v4.
With lc39, it is possible to enable (experimentally) tracing.
=> feat: upgrade lc39

docs/10_Overview_and_Usage.md
=> fix broken links

CHANGELOG.md
Updated CHANGELOG with latest changes
=> docs(CHANGELOG): added swagger fixing

CHANGELOG.md, index.js
In this PR the following changes were made:
- collection definition validation  is now carried out only once. The property `schema` is looked up for selecting which collection definition model it should be employed
- the CHANGELOG has been updated
=> fix: collection definition validation

docs/50_Writable_views.md
=> docs(core): fix typos and syntax

CHANGELOG.md
Removed link to internal documentation to avoid doc-aggregator errors.
=> docs(core): removed internal link changelog

CHANGELOG.md, Dockerfile, index.js, lib/httpInterface.js, lib/joinPlugin.js, package-lock.json, package.json, tests/httpInterface.changeStateBulk.test.js, tests/httpInterface.patchById.special.test.js, tests/httpInterface.postBulk.test.js, tests/httpInterface.postList.test.js
Reverts mia-platform/crud-service#118
=> Revert "Rollback to lc39 v6"

.github/workflows/nodejs.yml, Dockerfile, package-lock.json
Upgrade NodeJS Docker image to the latest LTS image (v18.16.1).
In addition, a pipeline trigger is created to execute further security checks.
=> ci+build: update node docker image

CHANGELOG.md
=> docs(CHANGELOG): fixed broken link

CHANGELOG.md, index.js, lib/JSONSchemaGenerator.js, tests/expectedSchemas/booksGetItemSchema.js, tests/expectedSchemas/booksNewGetItemSchema.js, tests/expectedSchemas/carsGetItemSchema.js, tests/expectedSchemas/carsNewGetItemSchema.js, tests/expectedSchemas/stationsGetItemSchema.js, tests/expectedSchemas/stationsNewGetItemSchema.js, tests/httpInterface.getById.test.js
The Schema of the response for the `GET /:id` method now does not accept additionalProperties, meaning that it will not possible to show fields of a document not defined in the JsonSchema by adding them in the `_p` query parameter.
I think this can be considered as a breaking change, considering that user might add logic behind the expectation that documents might contains fields included in the `_p` query parameters, regardless their presence in the JSON Schema.
=> fix: avoid to return properties not included in JsonSchema after a GET /:id

.github/workflows/checks.yml, .github/workflows/main.yml, .github/workflows/tests.yml
Update Github Actions to latest version of NodeJS, coverallapps action config and consider testing also MongoDB v7
=> fix: review of ci to update to NodeJS v20

.github/dependabot.yml
In this PR is introduced a Dependabot [configuration](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) which allows to group packages updates together according to specific patterns.  
In this manner, Dependabot would open a single PR for the group, rather than creating one for each package that has to be updated.
=> ci(dependabot): add groups configuration

CHANGELOG.md, docs/60_Usage_Best_Practices.md, lib/httpInterface.js, lib/mimeTypeTransform.js, lib/transformers/csv.js, lib/transformers/excel.js, lib/transformers/json.js, lib/transformers/ndjson.js, package-lock.json, package.json, tests/httpInterface.getExport.test.js
This PR addresses #247 and implements export for `xlsx` and `xls` format
=> feat(#247): implemented xls and xlsx export format

docs/30_Encryption_configuration.md
The previously proposed script did not work all the times based on differences with locales; with LC_ALL it's ought to work everywhere
=> docs: fix rand string cmd for encryption to work everywhere

docs/60_Usage_Best_Practices.md
=> Replace external link ndjson.org

lib/JSONSchemaGenerator.js, tests/expectedSchemas/booksExportSchema.js, tests/expectedSchemas/booksGetItemSchema.js, tests/expectedSchemas/booksGetListLookupSchema.js, tests/expectedSchemas/booksGetListSchema.js, tests/expectedSchemas/booksNewExportSchema.js, tests/expectedSchemas/booksNewGetItemSchema.js, tests/expectedSchemas/booksNewGetListLookupSchema.js, tests/expectedSchemas/booksNewGetListSchema.js, tests/expectedSchemas/carsExportSchema.js, tests/expectedSchemas/carsGetItemSchema.js, tests/expectedSchemas/carsGetListLookupSchema.js, tests/expectedSchemas/carsGetListSchema.js, tests/expectedSchemas/carsNewExportSchema.js, tests/expectedSchemas/carsNewGetItemSchema.js, tests/expectedSchemas/carsNewGetListLookupSchema.js, tests/expectedSchemas/carsNewGetListSchema.js, tests/expectedSchemas/stationsExportSchema.js, tests/expectedSchemas/stationsGetItemSchema.js, tests/expectedSchemas/stationsGetListLookupSchema.js, tests/expectedSchemas/stationsGetListSchema.js, tests/expectedSchemas/stationsNewExportSchema.js, tests/expectedSchemas/stationsNewGetItemSchema.js, tests/expectedSchemas/stationsNewGetListLookupSchema.js, tests/expectedSchemas/stationsNewGetListSchema.js
In this PR I fixed the JSON schema generator logic: now the example regarding the projection query parameter is openapi compliant
=> Fix projection example in json schema generator

CHANGELOG.md, lib/compilers.js
This PR fixes a bug introduced with the last minor, where models starting with the same prefix will have colliding validation compilers.
=> fix: validator compiler function

package-lock.json, package.json, tests/compilers.test.js
This PR adds tests for validator compiler function.
=> add: compiler tests

index.js, lib/createIndexes.js, lib/loadModels.js, package-lock.json, package.json
In this PR is reverted back an undesired behavior that allowed the service to start even in case not all the indexes were successfully created. In addition, logs explaining the failure are introduced.  
In this manner it is easier for developers to understand the reason why the service is not starting and which is the cause of the issue.
=> fix(indexes): terminate the service logging the error when index creation fails

.github/workflows/dependency-review.yaml, .github/workflows/release-docker.yml
This PR will fix two typos introduced with the new pipelines. The first one in the dependency-review one and the second in the cosign step of the docker-release one.
=> Fix typos in dependency review and cosign pipelines

.github/workflows/main.yml, .github/workflows/release-docker.yml, .github/workflows/tag.yml, .nvmrc, CHANGELOG.md, Dockerfile, package-lock.json, package.json
This PR fixes a typo in a secret naming employed throughout the CI and introduce a new step to further scan the image for vulnerabilities.
=> ci: add image scanning

CHANGELOG.md
=> Update v7.2.0 CHANGELOG.md
